from app.models.user import User
from app.models.semester import Semester
from app.models.course import Course
from app.models.schedule import Schedule
from app.models.file import File
from app.models.todo import Todo
from app.models.ai_content import AIContent
from app.models.device import Device
from app.models.note import UserNote
from app.models.tutor_message import TutorMessage
from app.models.flashcard_status import UserFlashcardStatus
from app.models.syllabus_update_proposal import SyllabusUpdateProposal
